"use client";

import React, { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";
import TasteCard from "../../../components/TasteCard";
import { supabase } from "../../../lib/supabaseClient";

/**
 * PUBLIC SHARE PAGE (/app/share/[shareId]/page.jsx)
 * 
 * Purpose:
 * - A publicly shareable page displaying the taste card corresponding to `shareId`.
 * - Visitors can view the archetype and details, then click a CTA to take their own quiz.
 * 
 * Flow:
 * 1. Read `shareId` route parameter.
 * 2. Fetch the public taste profile from Supabase on load.
 * 3. Render the read-only `TasteCard` component.
 * 4. Display CTA button linking to `/` to let visitors start their own taste profiling.
 */
export default function PublicSharePage() {
  const { shareId } = useParams();

  // States
  const [profile, setProfile] = useState(null);
  const [isLoading, setIsLoading] = useState(true);

  // Fetch the profile from Supabase
  useEffect(() => {
    if (shareId) {
      fetchPublicProfile();
    }
  }, [shareId]);

  const fetchPublicProfile = async () => {
    setIsLoading(true);
    try {
      const { data, error } = await supabase
        .from("profiles")
        .select("profile_data")
        .eq("share_id", shareId)
        .single();

      if (error || !data) {
        console.error("Failed to load public profile from Supabase:", error);
        setIsLoading(false);
        return;
      }

      setProfile(data.profile_data);
      setIsLoading(false);
    } catch (error) {
      console.error("Failed to load public profile:", error);
      setIsLoading(false);
    }
  };

  if (isLoading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-slate-950 text-indigo-300">
        <p className="text-lg animate-pulse">Loading shared taste profile...</p>
      </div>
    );
  }

  return (
    <main className="min-h-screen py-12 px-6 flex flex-col items-center justify-center bg-slate-950 text-slate-100 space-y-8">
      <header className="text-center max-w-xl">
        <span className="text-xs uppercase tracking-widest text-indigo-400 font-bold px-3 py-1 bg-indigo-950/50 rounded-full border border-indigo-800">
          Shared Profile
        </span>
        <h1 className="text-3xl font-extrabold text-white mt-4">
          Check Out My Taste Profile!
        </h1>
        <p className="text-slate-400 mt-2">
          Here is my unique archetype generated by Find My Taste.
        </p>
      </header>

      {/* TasteCard Component (Read-Only) */}
      <div className="w-full max-w-sm rounded-3xl overflow-hidden shadow-2xl">
        <TasteCard profile={profile} />
      </div>

      <footer className="text-center space-y-4">
        <p className="text-sm text-slate-500">Curious what your taste archetype is?</p>
        <Link href="/" className="inline-block py-3 px-8 rounded-xl font-semibold bg-gradient-to-r from-indigo-600 to-violet-600 hover:from-indigo-500 hover:to-violet-500 text-white shadow-lg transition-all duration-200">
          Discover Your Taste Archetype
        </Link>
      </footer>
    </main>
  );
}
